# Generated by Django 5.1.2 on 2024-11-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toro_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountmodel',
            table='account',
        ),
        migrations.AlterModelTable(
            name='refreshtokenmodel',
            table='refresh_token',
        ),
        migrations.AlterModelTable(
            name='socialaccountmodel',
            table='social_account',
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
