# Generated by Django 5.1.2 on 2024-11-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toro_auth', '0002_alter_accountmodel_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_models', to='toro_auth.accountmodel'),
        ),
    ]
