# Generated by Django 5.1.2 on 2024-11-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toro_auth', '0003_usermodel_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
