# Generated by Django 5.1.2 on 2024-11-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toro_auth', '0004_accountmodel_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='refreshtokenmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='refreshtokenmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
